<a href="https://colab.research.google.com/github/asfdqwtdsva123/MachineLearningProgramming/blob/main/whiteWine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import openpyxl

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [31]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/기계학습/4주차 강의/winequality-white.csv', sep=';')
print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6 

In [32]:
X = df.drop(columns='quality')
y = df['quality']

In [33]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  
0      8.8  
1      9.5  
2     10.1  
3      9.9  
4      9.9

In [34]:
y.head()

0    6
1    6
2    6
3    6
4    6
Name: quality, dtype: int64

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [36]:
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
4685            7.2              0.26         0.32            10.4      0.062   
4589            5.4              0.29         0.38             1.2      0.029   
2700            6.5              0.46         0.31             5.0      0.027   
283             6.7              0.34         0.30            15.6      0.054   
1014            6.1              0.16         0.27            12.6      0.064   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
4685                 23.0                 114.0  0.99660  3.23       0.49   
4589                 31.0                 132.0  0.98895  3.28       0.36   
2700                 15.0                  72.0  0.99165  3.26       0.60   
283                  51.0                 196.0  0.99820  3.19       0.49   
1014                 63.0                 162.0  0.99940  3.66       0.43   

      alcohol  
4685     10.5  
4589     12.4  
2700     11.5  
283       9.3  
1014      8.9

In [37]:
y_train.head()

4685    5
4589    6
2700    7
283     5
1014    5
Name: quality, dtype: int64

In [38]:
# 로지스틱 회귀, KNN을 위한 스케일링

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [39]:
# 결정트리
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train_scaled, y_train)
y_pred = clf_dt.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred))

0.5795918367346938


In [40]:
# 랜덤포레스트
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred = rf.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred))

0.6581632653061225


In [41]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   4   5   0   0]
 [  0  10  26  12   3   0]
 [  0   7 170 106  12   0]
 [  0   3  91 264  46   5]
 [  0   0  16  78  86   3]
 [  0   0   3  15  13   2]]
0.5428571428571428


In [42]:
# 로지스틱회귀
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train_scaled, y_train)
y_pred = lr.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred))

0.5163265306122449


In [43]:

print(lr.coef_, lr.intercept_)

[[ 0.68457631  0.31084877 -0.2165577   0.12915751  0.56710719  0.28306239
   0.45877222  0.09341774  0.00353942 -0.11275693  0.32203665]
 [-0.46534529  0.61905046 -0.05968683 -1.5064902   0.25635522 -0.97202737
  -0.07698757  1.62326333 -0.39250348 -0.11393407 -0.4748777 ]
 [-0.46069417  0.30867293  0.07159647 -0.69006545  0.21715996 -0.09519809
   0.0287206   0.69817085 -0.46716395 -0.11725635 -0.94808035]
 [-0.46182316 -0.25746199  0.04597516 -0.085378    0.21910453 -0.00422568
  -0.02685682  0.18057608 -0.3386452   0.05114019 -0.14934926]
 [-0.13557355 -0.5051218  -0.04229271  0.82093824 -0.08304783  0.09072773
  -0.02824861 -1.03025466  0.00182855  0.24474071  0.04624591]
 [-0.1639345  -0.37629595  0.03960149  1.05456065  0.15891696  0.37411529
  -0.12220678 -0.98323432  0.05630456  0.14539362  0.47049704]
 [ 1.00279435 -0.09969243  0.16136413  0.27727725 -1.33559603  0.32354573
  -0.23319304 -0.58193902  1.13664011 -0.09732715  0.73352771]] [-2.67256301 -0.42635206  2.57970898  3.

In [44]:
import numpy as np
import matplotlib.pyplot as plt